### ISSUE TITLE
fail if no extent

### ISSUE THREAD

**Issue by pvgenuchten** [pvgenuchten/pyGeoDataCrawler#28]
```
File "/usr/local/lib/python3.12/dist-packages/geodatacrawler/schemas/iso19139/main.j2", line 77, in top-level template code
    {% if record['identification']['extents'].get('spatial') not in [None,''] %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/jinja2/environment.py", line 487, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'extents'

Failed to create metadata: portals/Africa/explorer.digitalearth.africa/portals/Africa/explorer.digitalearth.africa/dea_pc_s2_annual.xml/iso19139 'dict object' has no attribute 'extents' Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/geodatacrawler/metadata.py", line 208, in processPath
    xml_string = render_j2_template(md, template_dir=os.path.join(schemaPath,profile))
```

**Comment by pvgenuchten** [comment]
solved in 1.3.4
